In [57]:
import numpy as np

#BASIC OPERATION

In [58]:
array_1d = ([1,2,3,4,5])
array_2d = ([[1,2,3,4,5],[2,3,4,5,6]])
array_3d = ([[[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]]])

In [59]:
print('1-D array')
print(array_1d)
print('2-D array')
print(array_2d)
print('3-D array')
print(array_3d)


1-D array
[1, 2, 3, 4, 5]
2-D array
[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]
3-D array
[[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]]


Numpy.arange - This method creates an array with incrementing values. This function takes some parameters like start number, end number, incrementing step value, and datatype.

In [60]:
array1 = np.arange(6)
print(array1)

[0 1 2 3 4 5]


In [61]:
#creating an array with 2 unit difference between integers the given array starts from 4 and ends on 16
array2 = np.arange(4,16,2)
print(array2)

[ 4  6  8 10 12 14]


In [62]:
#creating an array of float datatype numbers
array3 = np.arange(4.2,5,0.2,dtype=float)
print(array3)

[4.2 4.4 4.6 4.8]


Numpy.eye - We use the eye method to create 2-Dimensional arrays in python. The parameters in this function are the rows and the columns of the matrix. The elements where row and column index are identical (i.e., i=j) are 1, and the rest are 0.

In [63]:
#creating a 2-D array of 3x3 shape if we give only one parameter, it constructs a square matrix of the given length
array4 = np.eye(3)
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
#creating a 2-D array with four rows and six columns
array5 = np.eye(4,6)
print(array5)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


Numpy.diag - To create a matrix with the elements along the diagonal, we use the diag function from the Numpy Library.

In [65]:
#The given elements will be filled in the main diagonal of the matrix
array1 = np.diag([4, 5, 6, 7])
print(array1)

# The given elements will be filled in the second right diagonal of the matrix
array2 = np.diag([4, 5, 6], 2)
print(array2)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]
[[0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [66]:
# The array3 will contain the diagonal elements of the given matrix
array3 = np.diag(np.array([[1,2], [3,4]]))
print(array3)

[1 4]


In [67]:
#ndim - get dimension of array
print(array1.ndim)

2


In [68]:
# shape - number of elements stored in each dimension.
print(array1.shape)

(4, 4)


In [69]:
# size - total number of elements stored in the array.
print(array1.size)

16


In [70]:
#sorting elements in an array
#1-D array
array1 = np.array([12, 1, 60, 8, 100, 16])
sorted_array1 = np.sort(array1)
print("Sorted Array:\n", sorted_array1)

Sorted Array:
 [  1   8  12  16  60 100]


In [71]:
#2-D array
array2 = np.array([[12, 4, 6], [1, 0, 34]])
sorted_array2 = np.sort(array2, axis=0)
print("Column Sorted 2-D Array:\n", sorted_array2, "\n")

sorted_array3 = np.sort(array2, axis=1)
print("Row Sorted 2-D Array:\n", sorted_array3, "\n")

Column Sorted 2-D Array:
 [[ 1  0  6]
 [12  4 34]] 

Row Sorted 2-D Array:
 [[ 4  6 12]
 [ 0  1 34]] 



In [72]:
#unique - get unique values from the array
unique_array1 = np.unique(array1)
print(unique_array1)

[  1   8  12  16  60 100]


In [73]:
# flip - to reverse an array
array1 = np.array([12, 1, 60, 8, 100, 16])
flipped_array1 = np.flip(array1)
print(array1)
print(flipped_array1)

[ 12   1  60   8 100  16]
[ 16 100   8  60   1  12]


In [74]:
# reversing the rows of a two-dimensional array
rev_rows_array2 = np.flip(array2, axis=0)
print("Row reversed 2-D Matrix:\n", rev_rows_array2, "\n")

# reversing the columns of a two-dimensional array
rev_cols_array2 = np.flip(array2, axis=1)
print("Column reversed 2-D Matrix:\n", rev_cols_array2, "\n")

# reversing the entire content of the Matrix
rev_array2 = np.flip(array2)
print("Reversed 2-D Matrix:\n", rev_array2, "\n")


Row reversed 2-D Matrix:
 [[ 1  0 34]
 [12  4  6]] 

Column reversed 2-D Matrix:
 [[ 6  4 12]
 [34  0  1]] 

Reversed 2-D Matrix:
 [[34  0  1]
 [ 6  4 12]] 



#NUMPY DATATYPES

In [75]:
#creating array of integers
array_int = np.array([10,20,30],dtype=int)
print(array_int)

[10 20 30]


In [76]:
#creating array of float
array_float = np.array([3.14, 1.618, 2.718],dtype=float)
print(array_float)

[3.14  1.618 2.718]


In [77]:
#creating array of complex number
array_complex = np.array([1+2j, 3+4j, 5+6j],dtype=complex)
print(array_complex)

[1.+2.j 3.+4.j 5.+6.j]


In [78]:
#creating array of boolean values
array_bool = np.array([True, False, True],dtype=bool)
print(array_bool)


[ True False  True]


In [79]:
# Creating an array of half-precision floating-point numbers
half_float_array = np.array([3.14159, 2.71828], dtype=np.float16)
print(half_float_array)

[3.14  2.719]


In [80]:
#arange - creates arrays with regularly incrementing values.
np.arange(2,5,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9])

In [81]:
#linspace - create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#indexing and slicing

In [82]:
a = np.arange(10)
s = slice(2,7,2)
print(a[s])

[2 4 6]


In [83]:
# slice items starting from index
import numpy as np
a = np.arange(10)
print (a[2:])

[2 3 4 5 6 7 8 9]


In [84]:
# slice items between indexes
import numpy as np
a = np.arange(10)
print (a[2:5])

[2 3 4]


In [85]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print (a)
print ('\n')

# this returns array of items in the second column
print (a[...,1] )
print ('\n')

# Now we will slice all items from the second row
print (a[1,...] )
print ('\n')

# Now we will slice all items from column 1 onwards
print ('The items column 1 onwards are:')
print (a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[2 4 5]


[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [86]:
originalarray = np.arange(12)
print("Original array :\n", originalarray)

# Reshaping array into 3 rows and 4 columns
reshapedarray1 = np.arange(12).reshape(3, 4)
print("\nReshaped array with 3 rows and 4 columns :\n\n",reshapedarray1)

# Reshaping array into 4 rows and 3 columns
reshapedarray2 = np.arange(12).reshape(4, 3)
print("\nReshaped array with 4 rows and 3 columns :\n",reshapedarray2)

Original array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array with 3 rows and 4 columns :

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped array with 4 rows and 3 columns :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#Iteration

In [87]:
# Create a 2-dimensional NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Iterating over elements in the 2D array
# Iterate over rows
for i in range(arr_2d.shape[0]):
   # Iterate over columns
   for j in range(arr_2d.shape[1]):
      print(arr_2d[i, j])

1
2
3
4
5
6
7
8
9


In [88]:
#efficient multidimensional iterator object that can be used to iterate over elements of arrays.
arr = np.array([[1, 2], [3, 4]])

# Iterate using nditer
for x in np.nditer(arr):
   print(x)

1
2
3
4


In [89]:
# arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

# Broadcasting addition operation
print("Broadcasting Iteration:")
for x, y in np.nditer([arr1, arr2]):
   print(x + y, end=' ')

Broadcasting Iteration:
11 22 33 

#String Operation

In [90]:
s1 = np.array(['Hello','World'])
s2 = np.array(['World','Bad'])

ans = np.char.add(s1,s2)
print(ans)

['HelloWorld' 'WorldBad']


In [91]:
string = np.array(['Wow'])
ans = np.char.multiply(string,3)
print(ans)

['WowWowWow']


In [92]:
string = np.array(['hello','World'])
ans = np.char.capitalize(string)
print(ans)

['Hello' 'World']


In [93]:
lower = np.char.lower(string)
upper = np.char.upper(string)
print(lower)
print(upper)

['hello' 'world']
['HELLO' 'WORLD']


In [94]:
sent = np.array(['Hello World'])
ans = np.char.split(sent)
print(ans)

[list(['Hello', 'World'])]


#Joining Array

In [95]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [96]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [97]:
#hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [98]:
#vstack() to stack along columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [99]:
#dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


#Search

In [100]:
#search an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [101]:
# searchsorted() - performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [102]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])  #where the vaues should be inserted
print(x)

[1 2 3]


#Comparing and Filtering

In [103]:
a = np.array([1,2,3])
b = np.array([34,2,10])
out = np.equal(a,b)
print("The Boolean output of the equal function:",out)

The Boolean output of the equal function: [False  True False]


In [104]:
#greater() -  is used to compare any two NumPy arrays element-wise. This method returns True if the element in first array is greater than its corresponding element in the second array; and False, otherwise.
out = np.greater(a,b)
print("The Boolean output of the greater function:",out)

The Boolean output of the greater function: [False False False]


In [105]:
#delete() method is used to delete elements from a NumPy array, based on a condition specified by the user.
a = np.array([34,2,10])
filtered_array = np.delete(a, np.where(a == 2))
print("The output of the delete function :",filtered_array)

The output of the delete function : [34 10]


In [106]:
#extract() - extracts all the elements that satisfy the given condition, as its name implies.
a = np.array([34,2,10])
filtered_array = np.extract(a <=2, a)
print("The output of the extract function :",filtered_array)

The output of the extract function : [2]
